import type { ScheduleEvent } from "./types";

// The default mode focuses on premium 2026 PGA Tour starts: Signature Events,
// The Players, and the four majors. Future modes can swap this schedule object
// without changing the simulation runner.
export const PREMIUM_2026_SCHEDULE: ScheduleEvent[] = [
  {
    id: "sony-open",
    name: "Sony Open in Hawaii",
    kind: "regular",
    purse: 8_700_000,
    fedExBase: 500,
    fieldStrength: 0.42,
    volatility: 3.25,
  },
  {
    id: "pebble",
    name: "AT&T Pebble Beach Pro-Am",
    kind: "signature",
    purse: 20_000_000,
    fedExBase: 700,
    fieldStrength: 0.72,
    volatility: 2.75,
  },
  {
    id: "genesis",
    name: "Genesis Invitational",
    kind: "signature",
    purse: 20_000_000,
    fedExBase: 700,
    fieldStrength: 0.8,
    volatility: 2.95,
  },
  {
    id: "wm-phoenix-open",
    name: "WM Phoenix Open",
    kind: "regular",
    purse: 9_200_000,
    fedExBase: 500,
    fieldStrength: 0.58,
    volatility: 3.45,
  },
  {
    id: "arnold-palmer",
    name: "Arnold Palmer Invitational",
    kind: "signature",
    purse: 20_000_000,
    fedExBase: 700,
    fieldStrength: 0.82,
    volatility: 3,
  },
  {
    id: "players",
    name: "The Players Championship",
    kind: "players",
    purse: 25_000_000,
    fedExBase: 750,
    fieldStrength: 0.92,
    volatility: 3.15,
  },
  {
    id: "valspar",
    name: "Valspar Championship",
    kind: "regular",
    purse: 8_700_000,
    fedExBase: 500,
    fieldStrength: 0.46,
    volatility: 3.25,
  },
  {
    id: "houston-open",
    name: "Texas Children's Houston Open",
    kind: "regular",
    purse: 9_500_000,
    fedExBase: 500,
    fieldStrength: 0.5,
    volatility: 3.3,
  },
  {
    id: "masters",
    name: "Masters Tournament",
    kind: "major",
    purse: 22_500_000,
    fedExBase: 750,
    fieldStrength: 0.96,
    volatility: 3.25,
  },
  {
    id: "rbc-heritage",
    name: "RBC Heritage",
    kind: "signature",
    purse: 20_000_000,
    fedExBase: 700,
    fieldStrength: 0.76,
    volatility: 2.85,
  },
  {
    id: "cadillac",
    name: "Cadillac Championship",
    kind: "signature",
    purse: 20_000_000,
    fedExBase: 700,
    fieldStrength: 0.79,
    volatility: 2.9,
  },
  {
    id: "truist",
    name: "Truist Championship",
    kind: "signature",
    purse: 20_000_000,
    fedExBase: 700,
    fieldStrength: 0.78,
    volatility: 2.9,
  },
  {
    id: "pga",
    name: "PGA Championship",
    kind: "major",
    purse: 18_500_000,
    fedExBase: 750,
    fieldStrength: 0.95,
    volatility: 3.25,
  },
  {
    id: "canadian-open",
    name: "RBC Canadian Open",
    kind: "regular",
    purse: 9_800_000,
    fedExBase: 500,
    fieldStrength: 0.52,
    volatility: 3.2,
  },
  {
    id: "memorial",
    name: "The Memorial Tournament",
    kind: "signature",
    purse: 20_000_000,
    fedExBase: 700,
    fieldStrength: 0.84,
    volatility: 3,
  },
  {
    id: "us-open",
    name: "U.S. Open",
    kind: "major",
    purse: 21_500_000,
    fedExBase: 750,
    fieldStrength: 0.98,
    volatility: 3.55,
  },
  {
    id: "travelers",
    name: "Travelers Championship",
    kind: "signature",
    purse: 20_000_000,
    fedExBase: 700,
    fieldStrength: 0.8,
    volatility: 2.8,
  },
  {
    id: "rocket-classic",
    name: "Rocket Classic",
    kind: "regular",
    purse: 8_800_000,
    fedExBase: 500,
    fieldStrength: 0.44,
    volatility: 3.35,
  },
  {
    id: "john-deere",
    name: "John Deere Classic",
    kind: "regular",
    purse: 8_400_000,
    fedExBase: 500,
    fieldStrength: 0.36,
    volatility: 3.25,
  },
  {
    id: "open",
    name: "The Open Championship",
    kind: "major",
    purse: 17_000_000,
    fedExBase: 750,
    fieldStrength: 0.97,
    volatility: 3.7,
  },
  {
    id: "wyndham",
    name: "Wyndham Championship",
    kind: "regular",
    purse: 8_200_000,
    fedExBase: 500,
    fieldStrength: 0.42,
    volatility: 3.2,
  },
];

// Playoff entry is handled in the simulation runner because each cutoff depends
// on the player's live FedEx rank after the preceding stage.
export const FEDEX_PLAYOFF_SCHEDULE: ScheduleEvent[] = [
  {
    id: "st-jude",
    name: "FedEx St. Jude Championship",
    kind: "playoff",
    purse: 20_000_000,
    fedExBase: 750,
    fieldStrength: 0.9,
    volatility: 3.1,
    fieldSize: 70,
  },
  {
    id: "bmw",
    name: "BMW Championship",
    kind: "playoff",
    purse: 20_000_000,
    fedExBase: 750,
    fieldStrength: 0.96,
    volatility: 3.05,
    fieldSize: 50,
  },
  {
    id: "tour-championship",
    name: "Tour Championship",
    kind: "playoff",
    purse: 25_000_000,
    // Finale awards no FedEx points — even-par start, best 72-hole score wins.
    fedExBase: 0,
    fieldStrength: 1,
    volatility: 2.75,
    fieldSize: 30,
  },
];
